name: Günlük Asistan Otomasyonu

on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-java:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Kopyala
        uses: actions/checkout@v4

      - name: Java JDK 17 Kur
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Maven bağımlılıklarını önbelleğe alarak hızlandırır

      - name: Maven ile Derle ve Çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          mvn clean compile
          mvn exec:java -Dexec.mainClass="org.example.Main"